maintainer        "Digital Pioneers N.V."
maintainer_email  "m.kamphausen@digitalpioneers.de"
license           "Apache 2.0"
description       "Installs image file size optimization tools"
version           "0.1.0"
recipe            "imageoptimization", "Installs image optimization tools"
recipe            "imageoptimization::advpng", "Installs advancecomp"
recipe            "imageoptimization::imgopt", "Installs imgopt and jfifremove only"
recipe            "imageoptimization::jpegtran", "Installs jpeg-tools"
recipe            "imageoptimization::optipng", "Installs optipng""
recipe            "imageoptimization::pngout", "Installs pngout"

supports "ubuntu"
